### PR TITLE
Coverage support

### LINKED ISSUE #102: Add Coverage support
We should be tracking test coverage. 

FYI, while investigating this I discovered that we still support Ruby 1.8.7 , which is so out of date that it should probably be dropped as part of this change.

### PR DESCRIPTION
**Pull request by itsmechlark**
Add `COVERALLS_REPO_TOKEN` environment to travis-ci

#102

### CODE REVIEW

**Comment by itsmechlark** [comment]
Dropped support to `ruby v1.8.71 and `ree` at travis-ci test.

halostatue/mime-types#28
halostatue/mime-types@954a46060c77ddcc72ee0d4017a32670fd6cce94

**Comment by ptrimble** [comment]
Awesome! Thanks for this. I believe I set the coverage at 100% (because I am ever an optimist) but I don't think that upping the coverage should be required as part of this PR. I am currently in the process of refactoring the entire codebase. As part of that I will make sure we hit 100% coverage.

Let me putz around with this over this weekend and I'll merge it up.

Question: does removing support for 1.8.7 and ree require a major version bump? What do people think? Gut feeling is 'yes'.

**Comment by itsmechlark** [comment]
Yes. 
I think we should support 2.2.0 and requiring ruby at gemspec >= 2.0 ruby. What do think?
Let's move that to a separate PR if you'll strongly agree.

**Comment by itsmechlark** [comment]
I think we're done.
Thank you.

**Comment by ptrimble** [comment]
Thanks for your patience on this. I'll bump to v2.0.0 as well.

**Pull request merged**
