### PR TITLE
Add caching

### PR DESCRIPTION
**Pull request by ghiculescu**
Based on https://github.com/alexdunae/holidays/pull/36

### CODE REVIEW

**Comment by ptrimble** [comment]
Hm, why does this still say that it cannot merge cleanly?

**Comment by ghiculescu** [comment]
Hmm, not sure. Any idea how I could check?

**Comment by ptrimble** [comment]
@ghiculescu Heya, this is next up on my things to check. There was an issue where the definitions had not been regenerated since the last full release so I imagine it is contributing somehow to the problem. I've resolved that now so hopefully the problem should be easier to diagnose.

**Comment by ptrimble** [comment]
Hi @ghiculescu , I'm going to go ahead and close this and open a new PR with Nathan's commits. I couldn't figure out what was going on with this branch...I'm not a super git master and to be honest it was just easier for me to try stuff off of master on my local machine.

Thanks for taking the time to give this a go, I really appreciate it! :+1:

**Comment by ghiculescu** [comment]
:+1:

**Pull request closed without merging**
